### ISSUE TITLE
when stealing code on internet

### ISSUE THREAD

**Issue by ghost** [erica/uidevice-extension#13]
when stealing code on internet, you might retain the license holder even if it's under BSD license. Blame, you like or not.

-- The Chief

**Comment by erica** [comment]
I'm not sure what you're talking about. Can you be more specific?

**Comment by ghost** [comment]
no need.

**Comment by erica** [comment]
You are throwing around extremely serious accusations. I would like the opportunity to respond.

**Comment by ghost** [comment]
Qui se sent morveux qu'il se mouche
