### ISSUE TITLE
Get IMEI on iPhone4S, but doesn't work.

### ISSUE THREAD

**Issue by honorfight** [erica/uidevice-extension#16]
With empty NSString returned.
Please fix it, we need IMEI. 
Thanks  a lot.

**Comment by honorfight** [comment]
My iPhone4S is a GSM version.

**Comment by erica** [comment]
Can you give me a compelling reason for needing this functionality?

**Comment by honorfight** [comment]
Our project is for mobile operators, use iPhone4S for them to test and optimize the network.They need to keep track of each test terminal, through the phone's IMEI and SIM's IMSI.
