### ISSUE TITLE
Unexpected results of a global search and replace

### ISSUE THREAD

**Issue by mlamb** [erica/uidevice-extension#2]
Commit hash: d9c447d71b8d8be33616f3f136f7b3d8779ca041 introduced an unexpected consequence due the use of a global search and replace of + with -.  The pointer arithmetic was altered, which results in incorrect information being reported for the MAC address.

Line 378:
-  sdl = (struct sockaddr_dl *)(ifm + 1);<br>
-  sdl = (struct sockaddr_dl *)(ifm - 1);

Line 380:
-  NSString *outstring = [NSString stringWithFormat:@"%02x:%02x:%02x:%02x:%02x:%02x", *ptr, *(ptr+1), *(ptr+2), *(ptr+3), *(ptr+4), *(ptr+5)];<br>
-  NSString *outstring = [NSString stringWithFormat:@"%02x:%02x:%02x:%02x:%02x:%02x", *ptr, *(ptr-1), *(ptr-2), *(ptr-3), *(ptr-4), *(ptr-5)];

**Comment by erica** [comment]
Fixed per suggestion.
