### ISSUE TITLE
Maybe a bug in UIDevice-Reachability.m ?

### ISSUE THREAD

**Issue by marciomeschini** [erica/uidevice-extension#3]
Hello Erica,

i don't know if it's really a bug or maybe my inexperience however i changed method 
- (void) showAlert: (id) formatstring,... (line 204)
  into 
- (void) showAlert: (id) formatstring,...

because it's invoked from performWiFiCheck on "self" and not on "UIDevice".
Thanks in advance for your great works and excuse my poor english.
marcio

**Comment by erica** [comment]
Fixed & thanks. Please check that I've gotten it right...
