### ISSUE TITLE
platformHasCapability()

### ISSUE THREAD

**Issue by dannys42** [erica/uidevice-extension#4]
Not sure how to send patches here on github... But here's a little function I found useful:
 <pre>
diff --git a/UIDevice-Hardware.h b/UIDevice-Hardware.h
index bbc1b36..0493f1c 100644
--- a/UIDevice-Hardware.h
+++ b/UIDevice-Hardware.h
@@ -62,7 +62,7 @@ typedef enum {
    UIDeviceFirmware4,
 } UIDeviceFirmware;

-enum {
+typedef enum {
    UIDeviceSupportsTelephony = 1 << 0,
    UIDeviceSupportsSMS = 1 << 1,
    UIDeviceSupportsStillCamera = 1 << 2,
@@ -92,7 +92,7 @@ enum {
    UIDeviceSupportsPiezoClicker = 1 << 26,
    UIDeviceSupportsVolumeButtons = 1 << 27,
    UIDeviceSupportsEnhancedMultitouch = 1 << 28, // http://www.boygeniusreport.com/2010/01/13/apples-tablet-is-an-iphone-on-steroids/
-};
+} UIDeviceCapability;

 /*
  NOT Covered:
@@ -107,6 +107,7 @@ enum {
- (NSUInteger) platformCapabilities;
- (NSString *) platformString;
- (NSString *) platformCode;
  +- (BOOL) platformHasCapability:(UIDeviceCapability)capability;
- (NSArray *) capabilityArray;

diff --git a/UIDevice-Hardware.m b/UIDevice-Hardware.m
index 449e4cf..412fb5f 100644
--- a/UIDevice-Hardware.m
+++ b/UIDevice-Hardware.m
@@ -472,6 +472,13 @@
    }
 }

+- (BOOL) platformHasCapability:(UIDeviceCapability)capability 
+{
-    if( ([self platformCapabilities] & capability) == capability )
-        return YES;
-    return NO;
  +}
  +
  - (NSArray *) capabilityArray
    {
    NSUInteger flags = [self platformCapabilities];
    </pre>

**Comment by erica** [comment]
Added
