### ISSUE TITLE
macaddress in UIDevice-Hardware.m won't compile with Device - 3.2 target

### ISSUE THREAD

**Issue by msqr** [erica/uidevice-extension#5]
UIDevice-Hardware.m fails to compile in the iPhone 3.2b2 SDK. I was wondering if this is from bugs in the SDK, or if perhaps there are changes possible to correct the errors.

**Comment by msqr** [comment]
I should have poked around a little longer before I posted this. I found that adding

#include <sys/socket.h>

as the first #include solved the problem.

**Comment by erica** [comment]
Adding per suggestion. Thanks.
