### ISSUE TITLE
iPad model code

### ISSUE THREAD

**Issue by atomicbird** [erica/uidevice-extension#6]
The -platformCode method shows @"K48" as the model code for a 1st-gen wifi iPad.  I'm getting "K48AP".  This is from using sysctlbyname() to look up the value for hw.model.  I'd suggest that the entire -platformCode method could be replaced by this call, which would have the benefit of never needing to return IPOD_FAMILY_UNKNOWN_DEVICE.  The existing -getSysInfoByName: should be adequate-- just call it with "hw.model".

**Comment by cliffjoyce** [comment]
Anyone know of a way to distinguish between the WiFi and WiFi+3G iPad models?  I was hoping that Erica's uidevice-extension would solve this for me.  ;-)

**Comment by erica** [comment]
Added

// Thanks, Atomicbird
- (NSString *) hwmodel
  {
  [return [self getSysInfoByName:"hw.model"];
  }

**Comment by cliffjoyce** [comment]
Unfortunately, hwmodel is "K48AP" on both the iPad WiFi and WiFi+3G models.  Thanks for attempting a solution, but this one doesn't seem to help distinguish between the two models.
