### ISSUE TITLE
iPhone 4 support (and future iPhone support)

### ISSUE THREAD

**Issue by cdonnellytx** [erica/uidevice-extension#7]
Currently the library doesn't provide device capability detection for iPhone 4.

While there is a UIDevice4GiPhone constant used if the hardware string "iPhone3,1" is detected, -[UIDevice platformCapabilities] returns 0 because it is not considered.
# Chris

**Comment by cdonnellytx** [comment]
I checked in a fix on our company's fork (vauto/uidevice-extension).  Can you integrate it into the main code base?

Thanks,

# Chris

**Comment by erica** [comment]
Added. Thanks — E

**Comment by cdonnellytx** [comment]
Cool... although, aren't you or-ing the bits from different enums?

E.g.: for 1G iPhone:
             UIDeviceCommoSupportsTelephony |
             UIDeviceCommoSupportsSMS |
             UIDeviceCommoSupportsWifi |
             UIDeviceCommoSupportsBluetooth | // M68.plist says YES for this
             // UIDeviceCommoSupportsPeerToPeer |
             UIDeviceAudioSupportsBuiltInSpeaker |
             UIDeviceAudioSupportsVibration |
             // UIDeviceAudioSupportsPiezoClicker |
             UIDeviceAudioSupportsHardwareVolumeButtons |

If the flags are defined as:
        // Communication
        enum {
            UIDeviceCommoSupportsTelephony = 1 << 0,
            UIDeviceCommoSupportsSMS = 1 << 1,
            UIDeviceCommoSupportsWifi = 1 << 2,
            UIDeviceCommoSupportsBluetooth = 1 << 3,
            UIDeviceCommoSupportsPeerToPeer = 1 << 4,
        };

```
    // Audio
    enum {
        UIDeviceAudioSupportsBuiltInSpeaker = 1 << 0,
        UIDeviceAudioSupportsVibration = 1 << 1,
        UIDeviceAudioSupportsPiezoClicker = 1 << 2,
        UIDeviceAudioSupportsHardwareVolumeButtons = 1 << 3,
        UIDeviceAudioSupportsEncodeAAC = 1 << 4,
    };
```

then wouldn't it be saying the iPhone 1G has a piezo clicker, which is not the desired answer?

EDIT: code formatting.

**Comment by erica** [comment]
I've completely changed capability support, moved it to its own category, and will soon be pre-computing these on a device-by-device basis — right now the category is not App Store safe. Thanks for the catch; the new approach is far more thorough and accurate capability-wise
